# Generated by Django 2.0.2 on 2018-03-07 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LoanReason', models.CharField(max_length=25)),
                ('Amount', models.FloatField()),
                ('Discription', models.TextField()),
                ('date', models.DateTimeField()),
            ],
        ),
    ]
